### ISSUE TITLE
how to backup headless wallet and restore the wallet in the new server?

### ISSUE THREAD

**Issue by knight2008** [byteball/headless-byteball#39]
Hello,

I install the Headless  Wallet in my server A. I worried that server A was hacked by others. 
So I want to backup the Headless Wallet to my laptop. 
1. Which files I need to save？
2. How can I restore the Headless Wallet in another new server?

**Comment by knight2008** [comment]
I generate about 1000 new address with Headless Wallet, and  I send and receive some transactions via  Headless Wallet in my server A.

**Comment by tarmo888** [comment]
Headless wallet has 2 levels of security, keys.json and password. The keys.json is encrypted if your wallet was protected with password.

So, if they didn't get you wallet password then your funds are probably safe even if they got access to your files. So, you could simply copy all files in /home/username/.config/headless-obyte folder (database, conf, keys) to new server and install clean headless-obyte on new server because there is a possibility that they could edited your current installation with code that could log your password.

But to be safe, when you restore your wallet on new server, it recommended that you transfer your funds to completely new wallet, which would have totally new keys.json file and password that the hackers don't have.

**Comment by knight2008** [comment]
@tarmo888 Hello.  
In fact, I am a small exchange developer. I describe the detail user case here. 
1. I install the Headless wallet(full data mode) on Server A and create 1000 address for each user. 
	Then it will sync all the data real time.
2. But at the same time, maybe some user will send coins to my headless wallet on Server A, and I send coins to other user.
	So it will generate some change address on Server A, and I do not know the time the transactions generated.
3. At last, my question is: How can I backup the wallet on server A and then I can restore it on Server B if Server A breakdown.
	I do not think I can backup the 100G data from Server A, because it will change any time possibly.
4. Could I backup the conis like BTC, I can backup only wallet.dat every time generate transactions.
	So if I only backup keys.json, could I restore my coins on another Server.

**Comment by tarmo888** [comment]
keys.json only holds (encrypted if password is used) master seed that all the other addresses are derived from.

All the addresses that you have generated are in the `my_addresses` table. All the transactions are downloaded when you do the full sync again.

Maybe there are some other tables that need to be backed up that I am not aware, but I suggest you do join Discord #tech channel and post this link there, maybe somebody knows more how to handle cases like yours. https://discord.gg/ZmXMMdu

**Comment by luxalpachain** [comment]
Please close this ticket.
I found solution for sendtoaddress via static change address.
Add in conf.js and then only backup changeaddress and new addresses.
Do not need to backup sqlite realtime. 
exports.bStaticChangeAddress=true;

**Comment by tonyofbyteball** [comment]
You need to back up only the seed from keys.json and your password.  Then, if you don't use private assets or contracts, you can restore the wallet with all its addresses using the recovery script https://github.com/byteball/headless-obyte/blob/master/tools/recovery.js
