### ISSUE TITLE
Customize transaction fee.

### ISSUE THREAD

**Issue by hamza-kakar** [byteball/headless-byteball#41]
how can i change the transaction fee to zero.?
kindly anyone guide me.
thanks

**Comment by Papabyte** [comment]
I'm afraid you cannot, there is no marketplace for fees as in other cryptos. The transaction fee is a fixed rate: 1 byte = 1 byte.

**Comment by hamza-kakar** [comment]
i am working on a new project build using this opensource byteBall.
i need help in developers prospective. 
is there any way to do it.? as dagcoin are not using 1 byte = 1 byte mechanism.

**Comment by Papabyte** [comment]
It will be very complicated from a technical point of view since it never was intended to be configurable. Also transaction fees are an essential mechanism to keep the DAG narrow.
DAGcoin is a fork of Obyte but they run their own network, fees are paid in their own currency following the same mechanism. By the way, DAGcoin is only a support for a pyramid sales business, you shouldn't take them as technical reference.

**Comment by hamza-kakar** [comment]
That for quick response sir. 
can you little more elaborate, i mean why should we keep the DAD narrow.? what i have noticed is that transaction fees of every transaction is some x times of the fees of last transaction performed by same wallet id.

**Comment by tarmo888** [comment]
Don't try to guess how the fees work, read it from the whitepaper how they work, chapter 13, page 17
https://obyte.org/Byteball.pdf
